/* File generated with Shader Minifier 1.2
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAGMENT_INL_
# define FRAGMENT_INL_
# define VAR_M "v"
# define VAR_O "f"

const char *fragment_frag =
 "#version 130\n"
 "#define DEFAULT_MATERIAL_ID 0\n"
 "#define CAR_MATERIAL_ID 1\n"
 "#define STEERING_WHEEL_MATERIAL_ID 2\n"
 "#define TERRAIN_MATERIAL_ID 3\n"
 "#define GUARDRAIL_MATERIAL_ID 4\n"
 "#define TREE_TRUNK_MATERIAL_ID 5\n"
 "#define TREE_LEAF_MATERIAL_ID 6\n"
 "#define HOUSE_BODY_MATERIAL_ID 7\n"
 "#define HOUSE_ROOF_MATERIAL_ID 8\n"
 "uniform int v;"
 "out vec4 f;"
 "float m=1e4,i=3.1415926,y=v/float(44100);"
 "int c=0;"
 "vec2 x,z,d;"
 "float s(float v)"
 "{"
   "return v=fract(v*.1031),v*=v+33.33,v*=v+v,fract(v);"
 "}"
 "float t(vec2 v)"
 "{"
   "vec3 f=fract(vec3(v.xyx)*.1031);"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.x+f.y)*f.z);"
 "}"
 "vec2 n(vec2 v)"
 "{"
   "vec3 f=fract(vec3(v.xyx)*vec3(.1031,.103,.0973));"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.xx+f.yz)*f.zy);"
 "}"
 "float p(vec2 v)"
 "{"
   "vec2 c=floor(v),f=v-c;"
   "float i=t(c),z=t(c+vec2(1,0)),x=t(c+vec2(0,1)),d=t(c+vec2(1,1));"
   "vec2 m=smoothstep(vec2(0),vec2(1),f);"
   "return mix(mix(i,z,m.x),mix(x,d,m.x),m.y);"
 "}"
 "mat3 r(float v)"
 "{"
   "return mat3(1.,0.,0.,0.,cos(v),-sin(v),0.,sin(v),cos(v));"
 "}"
 "mat3 e(float v)"
 "{"
   "return mat3(cos(v),0.,sin(v),0.,1.,0.,-sin(v),0.,cos(v));"
 "}"
 "mat3 h(float v)"
 "{"
   "return mat3(cos(v),-sin(v),0.,sin(v),cos(v),0.,0.,0.,1.);"
 "}"
 "float e(vec3 v,vec3 D)"
 "{"
   "vec3 f=abs(v)-D;"
   "return length(max(f,0.))+min(max(f.x,max(f.y,f.z)),0.);"
 "}"
 "float h(inout vec2 v,float m)"
 "{"
   "float f=2*i/m,c=atan(v.y,v.x)+f/2,x=floor(c/f);"
   "c=mod(c,f)-f/2.;"
   "v=vec2(cos(c),sin(c))*length(v);"
   "if(abs(x)>=m/2)"
     "x=abs(x);"
   "return x;"
 "}"
 "float n(inout float v,float D)"
 "{"
   "float c=round(v/D);"
   "v=v-c*D;"
   "return c;"
 "}"
 "vec2 p(inout vec2 v,vec2 D)"
 "{"
   "vec2 c=round(v/D);"
   "v=v-c*D;"
   "return c;"
 "}"
 "float e(float v,float f,float c)"
 "{"
   "c*=4.;"
   "float i=max(c-abs(v-f),0.);"
   "return min(v,f)-i*i*.25/c;"
 "}"
 "float r(vec3 v,vec2 f)"
 "{"
   "vec2 c=vec2(length(v.xz)-f.x,v.y);"
   "return length(c)-f.y;"
 "}"
 "float h(vec3 v,float f,float c)"
 "{"
   "return mix(length(v.xz)-f,length(vec3(v.x,abs(v.y)-c,v.z))-f,step(c,abs(v.y)));"
 "}struct Map_Result{float dist;int mat_id;};"
 "void n(inout Map_Result v,float c,int m)"
 "{"
   "if(c<v.dist)"
     "v.dist=c,v.mat_id=m;"
 "}"
 "float M(vec3 v)"
 "{"
   "v*=r(-.05*i);"
   "float f=r(v*r(.5*i),vec2(.53,.075));"
   "vec3 c=v;"
   "h(c.xy,4.);"
   "c-=vec3(.22,0,0);"
   "f=e(f,e(c,vec3(.31,.05,.05)-.03)-.02,.008);"
   "f=min(f,e((v-vec3(0,-.05,.2))*r(-.05*i),vec3(.05,.05,.22)));"
   "return f;"
 "}"
 "void M(inout Map_Result v,vec3 c)"
 "{"
   "vec3 f=c;"
   "f.x=abs(f.x);"
   "n(v,M(c-vec3(-1.1,-.1,.2)),STEERING_WHEEL_MATERIAL_ID);"
   "float x=e((c-vec3(0,-1.05,1.5))*r(-.05*i),vec3(2.5,1,1))-.02;"
   "x=e(x,e((c-vec3(0,-.1,1.7))*r(-.05*i),vec3(2.4,.01,1))-.05,.02);"
   "x=e(x,e((f-vec3(2.7,0,1.15))*r(.2*i),vec3(.1,2.3,.1))-.08,.05);"
   "x=e(x,e(c-vec3(0,-.7,3),vec3(3.,.5,2))-.2,.01);"
   "float m=e(c-vec3(0,1.9,-2.),vec3(2.1,.1,2))-.02;"
   "n(v,e(x,m,.1),CAR_MATERIAL_ID);"
   "n(v,e(f-vec3(2.75,-2,-1),vec3(.1,2.,2.))-.2,CAR_MATERIAL_ID);"
 "}"
 "float s(vec2 v,vec2 f)"
 "{"
   "return v.x*f.y-v.y*f.x;"
 "}"
 "float M(vec2 v,vec2 f,vec2 c,vec2 i,out vec2 x)"
 "{"
   "vec2 m=f-i,d=i-c,D=c-f,z=d-D;"
   "f-=v;"
   "c-=v;"
   "i-=v;"
   "float y=s(f,i),a=s(c,f),p=s(i,c);"
   "vec2 t=2.*(a*d+p*D)-y*m;"
   "float M=(a*p-y*y*.25)/dot(t,t),l=clamp((.5*y+a+M*dot(t,z))/(y+a+p),0.,1.);"
   "vec2 T=f+l*(D+D+l*z);"
   "x=T+v;"
   "return length(T);"
 "}"
 "float t(vec2 v,inout vec2 f)"
 "{"
   "return M(v,x,z,d,f);"
 "}"
 "float a(vec2 v)"
 "{"
   "float f=p(v);"
   "f+=.5*p(2.*v);"
   "f+=.25*p(4.*v);"
   "f+=.125*p(8.*v);"
   "f+=.0625*p(16.*v);"
   "f+=.03125*p(32.*v);"
   "return f;"
 "}"
 "float a(vec2 v,float f)"
 "{"
   "float x=0,m=0.,i=1.;"
   "if(c==0)"
     "m=10.,i=.01;"
   "if(c==1)"
     "m=800.,i=3e-4,x=800.;"
   "if(c==2)"
     "m=100.,i=.003,x=100.;"
   "float z=m*a(i*v),D=mix(.001,1.,smoothstep(7.,200.,f));"
   "z=mix(x,z,D);"
   "if(c==2)"
     "{"
       "float d=mix(.001,1.,smoothstep(0.,100.,v.x));"
       "z=mix(z,0.,d);"
     "}"
   "return z;"
 "}"
 "vec3 w(vec2 v)"
 "{"
   "vec2 f=vec2(0,.05),D;"
   "float c=a(v,t(v,D)),x=a(v+f.yx,t(v+f.yx,D))-c,z=a(v+f.xy,t(v+f.xy,D))-c;"
   "return normalize(cross(vec3(0,z,f.y),vec3(f.y,x,0)));"
 "}"
 "vec3 T;"
 "mat3 D;"
 "mat3 w(vec3 v,vec3 f)"
 "{"
   "vec3 c=normalize(cross(f,v)),x=normalize(cross(c,f));"
   "return transpose(mat3(c,f,x));"
 "}"
 "mat2 H(float v)"
 "{"
   "float f=cos(v),x=sin(v);"
   "return mat2(f,x,-x,f);"
 "}"
 "void H(inout Map_Result v,vec3 f,float D)"
 "{"
   "f/=D;"
   "float c=m,i=1.;"
   "int x=TREE_TRUNK_MATERIAL_ID;"
   "while(i>.01)"
     "{"
       "f.x=abs(f.x);"
       "float z=max(abs(f.y-i*.5)-i*.4,length(f.xz))-i*.1;"
       "if(z<c)"
         "c=z,x=i>.03?TREE_TRUNK_MATERIAL_ID:TREE_LEAF_MATERIAL_ID;"
       "f.y-=i;"
       "f.xz*=H(1.6);"
       "f.zy*=H(.7);"
       "i*=.76;"
     "}"
   "float z=D*(c*.8);"
   "if(z<v.dist)"
     "v.dist=z,v.mat_id=x;"
 "}"
 "void H(inout Map_Result v,vec3 f,float c,float x,vec2 m)"
 "{"
   "if(c>=30.)"
     "for(int z=0;z<1;++z)"
       "for(int D=0;D<1;++D)"
         "{"
           "vec3 d=f;"
           "d.xz+=vec2(z,D)*m;"
           "vec2 y=p(d.xz,m*2.);"
           "float T=t(y);"
           "if(T<.5)"
             "d.xz+=m*(n(y)-.5),d*=e(2.*i*T),H(v,d-vec3(0,x,0),3.+2.*T);"
         "}"
 "}"
 "void M(inout Map_Result v,vec3 c,vec3 f)"
 "{"
   "float x=e(c,f)-.01;"
   "n(v,x,HOUSE_BODY_MATERIAL_ID);"
   "vec3 z=c-vec3(0,f.y+6.,0);"
   "z.x=abs(z.x);"
   "z*=h(i/6);"
   "float m=e(z,vec3(f.x+2.5,.5,f.z+.5))-.01;"
   "n(v,m,HOUSE_ROOF_MATERIAL_ID);"
 "}"
 "void H(inout Map_Result v,vec3 f)"
 "{"
   "vec2 D;"
   "float x=t(f.xz,D),z=a(f.xz,x);"
   "if(c!=0)"
     "{"
       "n(v,max(abs(7.2-x)-.13+.03*pow(cos(10.*f.y),2.),abs(f.y-.6-z)-.2),GUARDRAIL_MATERIAL_ID);"
       "vec3 m=vec3(7.2-x,f.y,mod(D.y+1.5,3.)-1.5);"
       "n(v,e(m,vec3(.1,.6,.2)),GUARDRAIL_MATERIAL_ID);"
     "}"
   "if(c==0)"
     "{"
       "{"
         "vec3 m=f;"
         "m.x=abs(m.x);"
         "m.x-=35.;"
         "float y=n(m.z,40.),d=s(y),p=s(y+37.2);"
         "m.y-=z+3.5;"
         "m*=e(.5*i);"
         "M(v,m,vec3(10.,4.5+10.*d,10.+10.*p));"
       "}"
       "H(v,f,x+25.,z,vec2(30.));"
     "}"
   "else"
     " if(c==1)"
       "H(v,f,x,z,vec2(5.));"
   "n(v,f.y-z,TERRAIN_MATERIAL_ID);"
 "}"
 "Map_Result l(vec3 v)"
 "{"
   "Map_Result f;"
   "f.dist=m;"
   "f.mat_id=DEFAULT_MATERIAL_ID;"
   "vec3 x=v;"
   "x-=T;"
   "\n#if 1\n"
   "x*=transpose(D);"
   "x-=vec3(1.2,-.7,1.2);"
   "M(f,x);"
   "H(f,v);"
   "\n#else\n"
   "M(f,x-vec3(0,0,28));"
   "\n#endif\n"
   "return f;"
 "}"
 "float a(in vec3 v,in vec3 f,float m,float c,float i)"
 "{"
   "float x=1.,z=1e20,D=m;"
   "for(int y=0;y<256&&D<c;y++)"
     "{"
       "float d=l(v+f*D).dist;"
       "if(d<.001)"
         "return 0.;"
       "float p=d*d/(2.*z),s=sqrt(abs(d*d-p*p));"
       "x=min(x,s/(i*max(0.,D-p)));"
       "z=d;"
       "D+=d;"
     "}"
   "return x;"
 "}"
 "vec3 l(vec3 v,float f)"
 "{"
   "vec2 m=vec2(s(f+1.),s(f+2.));"
   "float c=m.x*i*2.,x=m.y*2.-1.;"
   "vec3 z=vec3(sin(c),cos(c),x)/sqrt(1.+x*x);"
   "return z*sign(dot(z,v));"
 "}"
 "float H(vec3 v,vec3 f,float c,float x)"
 "{"
   "float i=0.;"
   "for(int z=0;z<10;z++)"
     "{"
       "float D=s(float(z))*c;"
       "vec3 m=normalize(f+l(f,D)*.95)*D;"
       "i+=(D-l(v+m).dist)/pow(1.+D,x);"
     "}"
   "return clamp(1.-i*.1,0.,999.);"
 "}"
 "vec3 S(vec3 v)"
 "{"
   "vec3 f=vec3(.001,0.,0.);"
   "return normalize(vec3(l(v+f.xyy).dist-l(v-f.xyy).dist,l(v+f.yxy).dist-l(v-f.yxy).dist,l(v+f.yyx).dist-l(v-f.yyx).dist));"
 "}"
 "vec4 M(vec2 v,vec2 f,vec2 c,float D)"
 "{"
   "vec4 m;"
   "float x=1.-D;"
   "m.xy=x*x*v+2*x*D*f+D*D*c;"
   "m.zw=(2*D-2)*v+(2-4*D)*f+2*D*c;"
   "return m;"
 "}"
 "vec3 S(vec3 v,float f,float x)"
 "{"
   "return v+(vec3(1)-v)*pow(1.-f,x);"
 "}"
 "vec2 G(vec2 v)"
 "{"
   "vec2 f=fract(v),x=floor(v);"
   "float c=100.,z=0.;"
   "for(int i=-1;i<=1;i++)"
     "for(int D=-1;D<=1;D++)"
       "{"
         "vec2 m=vec2(float(D),float(i)),d=x+m,y=n(d);"
         "float T=distance(f,y+m);"
         "if(T<c)"
           "c=T,z=t(d);"
       "}"
   "return vec2(max(0.,1.-c),z);"
 "}"
 "float G(vec3 v,vec3 f,float m)"
 "{"
   "float c=0.,x=.5;"
   "for(int i=0;i<5;++i)"
     "{"
       "float D=m*float(i+1);"
       "vec3 z=v+D*f;"
       "float d=l(z).dist;"
       "c+=x*(d/D);"
       "x/=2.;"
       "m*=2.;"
     "}"
   "return c;"
 "}"
 "vec3 a(vec3 v,vec3 f,vec3 x)"
 "{"
   "vec3 i=1.2*vec3(.5,.6,.7),z=vec3(0.,.1,.3);"
   "float m=max(0,v.y);"
   "vec3 D=mix(i,z,1.-exp(-5.*m));"
   "if(c==2)"
     "{"
       "f=1.5*vec3(.9,.5,.2);"
       "i=.5*vec3(.8,.05,.05);"
       "z=vec3(.25,.2,.5);"
       "float y=m-.23*(1./(.8+2.*pow(v.x-x.x,2.)));"
       "D=mix(f,z,1.-exp(-3*y));"
       "D=mix(i,D,1.-exp(-5*m));"
       "{"
         "float d=max(0.,dot(v,x));"
         "d=smoothstep(.9995,1.,d);"
         "D=mix(D,2.*f,d);"
       "}"
     "}"
   "return D;"
 "}"
 "void main()"
 "{"
   "vec2 v=vec2(1920,1080),i=gl_FragCoord.xy/v.xy,r=-1.+2.*i;"
   "r.x*=v.x/v.y;"
   "T=vec3(0,1.6,-2);"
   "float n=y-t(gl_FragCoord.xy+y)/200.;"
   "const float s=1.5;"
   "float C=n;"
   "if(y<12.5)"
     "c=0,x=vec2(0,0),z=vec2(0,500),d=vec2(1,1000);"
   "else"
     " if(y<23.5)"
       "c=1,x=vec2(0,0),z=vec2(0,1000),d=vec2(1500,2000),C=n-12.5;"
     "else"
       " c=2,x=vec2(0,4000),z=vec2(0,8000),d=vec2(-100,12000),C=n-23.5;"
   "vec4 e=M(x,z,d,C/30.);"
   "T.xz+=e.xy;"
   "vec2 h;"
   "T.y+=a(T.xz,t(T.xz,h));"
   "vec3 k=normalize(cross(vec3(e.z,0,e.w),w(T.xz)));"
   "T-=2.*k;"
   "vec3 b=T;"
   "b.y+=.01*p(vec2(50*y,0));"
   "D=w(vec3(e.z,0,e.w),w(T.xz));"
   "vec3 o=normalize(vec3(r.x,r.y,1.7))*D;"
   "float A=0.;"
   "int g=-1;"
   "for(int R=0;R<1024&&A<m;++R)"
     "{"
       "Map_Result E=l(b+A*o);"
       "float I=E.dist;"
       "if(abs(I)<.001*(1.+A))"
         "{"
           "g=E.mat_id;"
           "break;"
         "}"
       "A+=I;"
     "}"
   "vec3 R=vec3(1.1,1.05,1.),E=vec3(.3,.35,.5),I=normalize(vec3(-.3,2.,1.));"
   "if(c==2)"
     "I=normalize(vec3(.2,.1,1.));"
   "vec3 u=a(o,R,I),L=u;"
   "if(g!=-1)"
     "{"
       "vec3 U=b+A*o,O=S(U);"
       "vec2 N;"
       "float F=t(U.xz,N);"
       "bool W=false;"
       "vec3 K=vec3(1);"
       "if(g==CAR_MATERIAL_ID)"
         "K=vec3(.05);"
       "if(g==STEERING_WHEEL_MATERIAL_ID)"
         "K=vec3(.05);"
       "if(g==TREE_TRUNK_MATERIAL_ID)"
         "K=.7*vec3(.13,.1,.05);"
       "if(g==TREE_LEAF_MATERIAL_ID)"
         "K=.7*vec3(.3,.4,.05);"
       "if(g==HOUSE_BODY_MATERIAL_ID)"
         "K=4.*vec3(.8,.7,.35);"
       "if(g==HOUSE_ROOF_MATERIAL_ID)"
         "K=vec3(.5,.18,.1);"
       "if(g==TERRAIN_MATERIAL_ID)"
         "if(F<=7.)"
           "{"
             "float Y=p(20.*U.xz);"
             "K=vec3(.1)+Y*vec3(.05);"
             "if(F<=.15)"
               "{"
                 "float B=step(1.3,mod(N.y,5.));"
                 "K=mix(K,vec3(.65),B);"
               "}"
             "if(F>6.3&&F<6.6)"
               "K=vec3(.65);"
             "W=true;"
           "}"
         "else"
           "{"
             "vec3 Y=.7*vec3(.35,.5,.05),B=.7*vec3(.45,.5,.05),q=mix(Y,B,p(.02*U.xz));"
             "q=mix(.3*q,q,G(2.*U.xz).x);"
             "vec3 Z=S(vec3(0),dot(O,-o),3.);"
             "q+=vec3(.2,.2,.1)*Z;"
             "q*=.8;"
             "K=q;"
           "}"
       "float Y=max(0,dot(O,I));"
       "L=K*Y*R*a(U+.001*O,I,.023,m,.03);"
       "L+=.15*K*E*H(U,O,1.5,1.);"
       "if(W)"
         "L+=.2*u*pow(clamp(1.+dot(O,o),0.,1.),10.);"
       "if(g>STEERING_WHEEL_MATERIAL_ID)"
         "{"
           "float B=a(U.xz,F),q=1./(1.+pow(U.y-B,2.));"
           "q*=max(0.,.5-.5*O.y);"
           "q*=H(U,O,1.5,1.);"
           "L+=.2*R*vec3(.3,.5,.1)*q;"
         "}"
       "if(c==2&&U.x>5.)"
         "{"
           "vec3 q=vec3(0,1,0);"
           "q+=.01*(a(.01*U.xz)-.5);"
           "vec3 B=reflect(o,q),Z=S(vec3(.2),dot(O,-o),5.);"
           "L=Z*a(B,R,I);"
         "}"
       "float q=pow(max(0,dot(o,I)),8.);"
       "L=mix(L,u,1.-exp(-5e-5*A));"
       "if(c!=2)"
         "L+=.1*R*q;"
     "}"
   "else"
     " if(c!=2)"
       "{"
         "float K=5e3-2e3*dot(o.xz,o.xz);"
         "vec3 U=b+o*(K/o.y);"
         "L=mix(L,vec3(1),max(0,a(2e-4*U.xz)-1.2));"
       "}"
   "if(y<s)"
     "L=vec3(0);"
   "f=vec4(sqrt(L),0.);"
 "}";

#endif // FRAGMENT_INL_
