/* File generated with Shader Minifier 1.2
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAGMENT_INL_
# define FRAGMENT_INL_
# define VAR_M "v"
# define VAR_O "f"

const char *fragment_frag =
 "#version 130\n"
 "uniform int v;"
 "out vec4 f;"
 "float y=1e3,x=3.1415926,m=v/float(44100);"
 "float s(float v)"
 "{"
   "return v=fract(v*.1031),v*=v+33.33,v*=v+v,fract(v);"
 "}"
 "float n(vec2 v)"
 "{"
   "vec3 f=fract(vec3(v.xyx)*.1031);"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.x+f.y)*f.z);"
 "}"
 "vec2 t(vec2 v)"
 "{"
   "vec3 f=fract(vec3(v.xyx)*vec3(.1031,.103,.0973));"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.xx+f.yz)*f.zy);"
 "}"
 "float e(vec2 v)"
 "{"
   "vec2 y=floor(v),f=v-y;"
   "float m=n(y),x=n(y+vec2(1,0)),c=n(y+vec2(0,1)),s=n(y+vec2(1,1));"
   "vec2 g=smoothstep(vec2(0),vec2(1),f);"
   "return mix(mix(m,x,g.x),mix(c,s,g.x),g.y);"
 "}"
 "float h(vec2 v)"
 "{"
   "float y=0.,f=.5;"
   "for(int r=0;r<5;++r)"
     "y+=f*e(v/f),f/=2.;"
   "return y;"
 "}"
 "mat3 r(float v)"
 "{"
   "return mat3(1.,0.,0.,0.,cos(v),-sin(v),0.,sin(v),cos(v));"
 "}"
 "mat3 l(float v)"
 "{"
   "return mat3(cos(v),0.,sin(v),0.,1.,0.,-sin(v),0.,cos(v));"
 "}"
 "mat3 p(float v)"
 "{"
   "return mat3(cos(v),-sin(v),0.,sin(v),cos(v),0.,0.,0.,1.);"
 "}"
 "float e(vec3 v,vec3 y)"
 "{"
   "vec3 f=abs(v)-y;"
   "return length(max(f,0.))+min(max(f.x,max(f.y,f.z)),0.);"
 "}"
 "float h(inout vec2 v,float y)"
 "{"
   "float f=2*x/y,r=atan(v.y,v.x)+f/2,m=floor(r/f);"
   "r=mod(r,f)-f/2.;"
   "v=vec2(cos(r),sin(r))*length(v);"
   "if(abs(m)>=y/2)"
     "m=abs(m);"
   "return m;"
 "}"
 "vec2 l(inout vec2 v,vec2 f)"
 "{"
   "vec2 y=floor((v+f*.5)/f);"
   "v=mod(v+f*.5,f)-f*.5;"
   "return y;"
 "}"
 "float e(float v,float f,float y)"
 "{"
   "y*=4.;"
   "float m=max(y-abs(v-f),0.);"
   "return min(v,f)-m*m*.25/y;"
 "}"
 "float n(vec3 v,float y)"
 "{"
   "return length(v)-y;"
 "}"
 "float p(vec3 v,vec2 f)"
 "{"
   "vec2 y=vec2(length(v.xz)-f.x,v.y);"
   "return length(y)-f.y;"
 "}"
 "float h(vec3 v,float y,float f)"
 "{"
   "return mix(length(v.xz)-y,length(vec3(v.x,abs(v.y)-f,v.z))-y,step(f,abs(v.y)));"
 "}"
 "float a(vec3 v)"
 "{"
   "v*=r(-.05*x);"
   "float f=p(v*r(.5*x),vec2(.53,.075));"
   "vec3 y=v;"
   "h(y.xy,4.);"
   "y-=vec3(.22,0,0);"
   "f=e(f,e(y,vec3(.31,.05,.05)-.03)-.02,.008);"
   "f=min(f,e((v-vec3(0,-.05,.2))*r(-.05*x),vec3(.05,.05,.22)));"
   "return f;"
 "}"
 "float d(vec3 v)"
 "{"
   "vec3 f=v;"
   "f.x=abs(f.x);"
   "float y=a(v-vec3(-1.1,-.1,.2)),m=e((v-vec3(0,-1.05,1.5))*r(-.05*x),vec3(2.5,1,1))-.02;"
   "m=e(m,e((v-vec3(0,-.1,1.7))*r(-.05*x),vec3(2.4,.01,1))-.1,.02);"
   "m=e(m,e((f-vec3(2.7,0,1.15))*r(.2*x),vec3(.1,2.3,.1))-.08,.05);"
   "m=e(m,e(v-vec3(0,-.7,3),vec3(3.,.5,2))-.2,.01);"
   "float s=e(v-vec3(0,1.9,-2.),vec3(2.1,.1,2))-.02;"
   "y=min(y,e(m,s,.1));"
   "y=min(y,e(f-vec3(2.75,-2,-1),vec3(.1,2.,2.))-.2);"
   "return y;"
 "}"
 "float c(vec2 v)"
 "{"
   "float y=40.*e(.01*v)-.5;"
   "return y;"
 "}"
 "vec3 i(vec2 v)"
 "{"
   "vec2 f=vec2(0,.05);"
   "float y=c(v),m=c(v+f.yx)-y,s=c(v+f.xy)-y;"
   "return normalize(cross(vec3(0,s,f.y),vec3(f.y,m,0)));"
 "}"
 "float w(vec3 v)"
 "{"
   "float f=c(v.xz);"
   "vec2 y=l(v.xz,vec2(5.,5.));"
   "v.xz+=4.*(t(y)-.5);"
   "float m=length(v-vec3(0,f,0))-.3;"
   "m=min(m,v.y-f);"
   "return m;"
 "}"
 "vec3 g;"
 "mat3 z;"
 "mat3 a(vec3 v,vec3 f)"
 "{"
   "vec3 y=normalize(cross(f,v)),m=normalize(cross(y,f));"
   "return transpose(mat3(y,f,m));"
 "}"
 "float o(vec3 v)"
 "{"
   "vec3 f=v;"
   "f-=g;"
   "f*=transpose(z);"
   "f-=vec3(1.2,-.7,1.2);"
   "float y=d(f);"
   "y=min(y,w(v));"
   "return y;"
 "}"
 "float a(in vec3 v,in vec3 y,float f,float m,float x)"
 "{"
   "float r=1.,s=1e20,z=f;"
   "for(int g=0;g<256&&z<m;g++)"
     "{"
       "float c=o(v+y*z);"
       "if(c<.001)"
         "return 0.;"
       "float l=c*c/(2.*s),a=sqrt(c*c-l*l);"
       "r=min(r,a/(x*max(0.,z-l)));"
       "s=c;"
       "z+=c;"
     "}"
   "return r;"
 "}"
 "vec3 c(vec3 v,float y)"
 "{"
   "vec2 f=vec2(s(y+1.),s(y+2.));"
   "float m=f.x*x*2.,z=f.y*2.-1.;"
   "vec3 c=vec3(sin(m),cos(m),z)/sqrt(1.+z*z);"
   "return c*sign(dot(c,v));"
 "}"
 "float a(vec3 v,vec3 y,float f,float m)"
 "{"
   "float r=0.;"
   "for(int x=0;x<10;x++)"
     "{"
       "float z=s(float(x))*f;"
       "vec3 l=normalize(y+c(y,z)*.95)*z;"
       "r+=(z-o(v+l))/pow(1.+z,m);"
     "}"
   "return clamp(1.-r*.1,0.,999.);"
 "}"
 "vec3 u(vec3 v)"
 "{"
   "vec3 f=vec3(.001,0.,0.);"
   "return normalize(vec3(o(v+f.xyy)-o(v-f.xyy),o(v+f.yxy)-o(v-f.yxy),o(v+f.yyx)-o(v-f.yyx)));"
 "}"
 "vec4 c(vec2 v,vec2 y,vec2 f,float m)"
 "{"
   "vec4 r;"
   "float c=1.-m;"
   "r.xy=c*c*v+2*c*m*y+m*m*f;"
   "r.zw=(2*m-2)*v+(2-4*m)*y+2*m*f;"
   "return r;"
 "}"
 "void main()"
 "{"
   "vec2 v=vec2(1280,720),s=gl_FragCoord.xy/v.xy,r=-1.+2.*s;"
   "r.x*=v.x/v.y;"
   "g=vec3(0,1.4,-2);"
   "float x=m-n(gl_FragCoord.xy+m)/200.;"
   "vec4 l=c(vec2(0,0),vec2(0,1000),vec2(1000,0),x/60.);"
   "g.xz+=l.xy;"
   "g.y+=c(g.xz);"
   "vec3 d=g;"
   "d.y+=.01*e(vec2(50*m,0));"
   "z=a(vec3(l.z,0,l.w),i(g.xz));"
   "vec3 w=normalize(vec3(r.x,r.y,1.7))*z;"
   "float t=0.;"
   "bool h=false;"
   "for(int b=0;b<256&&t<y;++b)"
     "{"
       "float p=o(d+t*w);"
       "if(abs(p)<.001*(1.+t))"
         "{"
           "h=true;"
           "break;"
         "}"
       "t+=p;"
     "}"
   "vec3 p=1.4*vec3(.5,.6,.7);"
   "p=mix(p,.5*p,w.y);"
   "vec3 b=p,q=normalize(vec3(-2.,1.,-1.));"
   "if(h)"
     "{"
       "vec3 F=d+t*w,C=u(F),k=vec3(1);"
       "b=.7*max(0.,dot(C,q))*k*a(F,q,.023,y,.05);"
       "b+=.15*p*a(F,C,1.5,1.);"
     "}"
   "f=vec4(sqrt(b),0.);"
 "}";

#endif // FRAGMENT_INL_
