/* File generated with Shader Minifier 1.2
 * http://www.ctrl-alt-test.fr
 */
#ifndef FRAGMENT_INL_
# define FRAGMENT_INL_
# define VAR_M "v"
# define VAR_O "f"

const char *fragment_frag =
 "#version 130\n"
 "#define DEFAULT_MATERIAL_ID 0\n"
 "#define CAR_MATERIAL_ID 1\n"
 "#define STEERING_WHEEL_MATERIAL_ID 2\n"
 "#define TERRAIN_MATERIAL_ID 3\n"
 "#define GUARDRAIL_MATERIAL_ID 4\n"
 "uniform int v;"
 "out vec4 f;"
 "float m=2e3,y=3.1415926,x=v/float(44100);"
 "float s(float v)"
 "{"
   "return v=fract(v*.1031),v*=v+33.33,v*=v+v,fract(v);"
 "}"
 "float t(vec2 v)"
 "{"
   "vec3 f=fract(vec3(v.xyx)*.1031);"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.x+f.y)*f.z);"
 "}"
 "vec2 n(vec2 v)"
 "{"
   "vec3 f=fract(vec3(v.xyx)*vec3(.1031,.103,.0973));"
   "f+=dot(f,f.yzx+33.33);"
   "return fract((f.xx+f.yz)*f.zy);"
 "}"
 "float e(vec2 v)"
 "{"
   "vec2 y=floor(v),f=v-y;"
   "float i=t(y),z=t(y+vec2(1,0)),m=t(y+vec2(0,1)),x=t(y+vec2(1,1));"
   "vec2 M=smoothstep(vec2(0),vec2(1),f);"
   "return mix(mix(i,z,M.x),mix(m,x,M.x),M.y);"
 "}"
 "float r(vec2 v)"
 "{"
   "float y=0.,f=.5;"
   "for(int r=0;r<5;++r)"
     "y+=f*e(v/f),f/=2.;"
   "return y;"
 "}"
 "mat3 d(float v)"
 "{"
   "return mat3(1.,0.,0.,0.,cos(v),-sin(v),0.,sin(v),cos(v));"
 "}"
 "mat3 h(float v)"
 "{"
   "return mat3(cos(v),0.,sin(v),0.,1.,0.,-sin(v),0.,cos(v));"
 "}"
 "mat3 p(float v)"
 "{"
   "return mat3(cos(v),-sin(v),0.,sin(v),cos(v),0.,0.,0.,1.);"
 "}"
 "float d(vec3 v,vec3 y)"
 "{"
   "vec3 f=abs(v)-y;"
   "return length(max(f,0.))+min(max(f.x,max(f.y,f.z)),0.);"
 "}"
 "float e(inout vec2 v,float f)"
 "{"
   "float m=2*y/f,i=atan(v.y,v.x)+m/2,D=floor(i/m);"
   "i=mod(i,m)-m/2.;"
   "v=vec2(cos(i),sin(i))*length(v);"
   "if(abs(D)>=f/2)"
     "D=abs(D);"
   "return D;"
 "}"
 "vec2 h(inout vec2 v,vec2 f)"
 "{"
   "vec2 m=floor((v+f*.5)/f);"
   "v=mod(v+f*.5,f)-f*.5;"
   "return m;"
 "}"
 "float d(float v,float f,float y)"
 "{"
   "y*=4.;"
   "float m=max(y-abs(v-f),0.);"
   "return min(v,f)-m*m*.25/y;"
 "}"
 "float n(vec3 v,float y)"
 "{"
   "return length(v)-y;"
 "}"
 "float p(vec3 v,vec2 y)"
 "{"
   "vec2 f=vec2(length(v.xz)-y.x,v.y);"
   "return length(f)-y.y;"
 "}"
 "float e(vec3 v,float y,float f)"
 "{"
   "return mix(length(v.xz)-y,length(vec3(v.x,abs(v.y)-f,v.z))-y,step(f,abs(v.y)));"
 "}struct Map_Result{float dist;int mat_id;};"
 "void h(inout Map_Result v,float f,int y)"
 "{"
   "if(f<v.dist)"
     "v.dist=f,v.mat_id=y;"
 "}"
 "float c(vec3 v)"
 "{"
   "v*=d(-.05*y);"
   "float f=p(v*d(.5*y),vec2(.53,.075));"
   "vec3 i=v;"
   "e(i.xy,4.);"
   "i-=vec3(.22,0,0);"
   "f=d(f,d(i,vec3(.31,.05,.05)-.03)-.02,.008);"
   "f=min(f,d((v-vec3(0,-.05,.2))*d(-.05*y),vec3(.05,.05,.22)));"
   "return f;"
 "}"
 "void c(inout Map_Result v,vec3 f)"
 "{"
   "vec3 i=f;"
   "i.x=abs(i.x);"
   "h(v,c(f-vec3(-1.1,-.1,.2)),STEERING_WHEEL_MATERIAL_ID);"
   "float m=d((f-vec3(0,-1.05,1.5))*d(-.05*y),vec3(2.5,1,1))-.02;"
   "m=d(m,d((f-vec3(0,-.1,1.7))*d(-.05*y),vec3(2.4,.01,1))-.05,.02);"
   "m=d(m,d((i-vec3(2.7,0,1.15))*d(.2*y),vec3(.1,2.3,.1))-.08,.05);"
   "m=d(m,d(f-vec3(0,-.7,3),vec3(3.,.5,2))-.2,.01);"
   "float z=d(f-vec3(0,1.9,-2.),vec3(2.1,.1,2))-.02;"
   "h(v,d(m,z,.1),CAR_MATERIAL_ID);"
   "h(v,d(i-vec3(2.75,-2,-1),vec3(.1,2.,2.))-.2,CAR_MATERIAL_ID);"
 "}"
 "vec2 i=vec2(0,0),z=vec2(0,1000),a=vec2(3000,1000);"
 "float r(vec2 v,vec2 y)"
 "{"
   "return v.x*y.y-v.y*y.x;"
 "}"
 "float c(vec2 v,vec2 f,vec2 y,vec2 m,out vec2 i)"
 "{"
   "vec2 d=f-m,x=m-y,D=y-f,z=x-D;"
   "f-=v;"
   "y-=v;"
   "m-=v;"
   "float M=r(f,m),c=r(y,f),s=r(m,y);"
   "vec2 a=2.*(c*x+s*D)-M*d;"
   "float l=(c*s-M*M*.25)/dot(a,a),T=clamp((.5*M+c+l*dot(a,z))/(M+c+s),0.,1.);"
   "vec2 t=f+T*(D+D+T*z);"
   "i=t+v;"
   "return length(t);"
 "}"
 "float s(vec2 v,inout vec2 f)"
 "{"
   "return c(v,i,z,a,f);"
 "}"
 "float t(vec2 v,float f)"
 "{"
   "float y=60.*e(.01*v)-.5;"
   "y+=20.*e(.02*v);"
   "y+=10.*e(.04*v);"
   "y+=5.*e(.1*v);"
   "y+=2.*e(.2*v);"
   "y=mix(.003,1.,smoothstep(7.,100.,f))*y;"
   "return y;"
 "}"
 "vec3 l(vec2 v)"
 "{"
   "vec2 f=vec2(0,.05),y;"
   "float m=t(v,s(v,y)),z=t(v+f.yx,s(v+f.yx,y))-m,i=t(v+f.xy,s(v+f.xy,y))-m;"
   "return normalize(cross(vec3(0,i,f.y),vec3(f.y,z,0)));"
 "}"
 "void l(inout Map_Result v,vec3 f)"
 "{"
   "vec2 y;"
   "float m=s(f.xz,y),z=t(f.xz,m);"
   "h(v,max(abs(7.2-m)-.13+.03*pow(cos(10.*f.y),2.),abs(f.y-.6-z)-.2),GUARDRAIL_MATERIAL_ID);"
   "vec3 i=vec3(7.2-m,f.y,mod(y.y+1.5,3.)-1.5);"
   "h(v,d(i,vec3(.1,.6,.2)),GUARDRAIL_MATERIAL_ID);"
   "\n#if 0\n"
   "if(m>=8.)"
     "{"
       "vec2 D=h(f.xz,vec2(2.,2.));"
       "f.xz+=2.*(n(D)-.5);"
       "h(v,length(f-vec3(0,z,0))-.1,TERRAIN_MATERIAL_ID);"
     "}"
   "\n#endif\n"
   "h(v,f.y-z,TERRAIN_MATERIAL_ID);"
 "}"
 "vec3 M;"
 "mat3 D;"
 "mat3 w(vec3 v,vec3 f)"
 "{"
   "vec3 m=normalize(cross(f,v)),y=normalize(cross(m,f));"
   "return transpose(mat3(m,f,y));"
 "}"
 "Map_Result w(vec3 v)"
 "{"
   "Map_Result f;"
   "f.dist=m;"
   "f.mat_id=DEFAULT_MATERIAL_ID;"
   "vec3 y=v;"
   "y-=M;"
   "y*=transpose(D);"
   "y-=vec3(1.2,-.7,1.2);"
   "c(f,y);"
   "l(f,v);"
   "return f;"
 "}"
 "float d(in vec3 v,in vec3 f,float m,float y,float i)"
 "{"
   "float r=1.,z=1e20,D=m;"
   "for(int M=0;M<256&&D<y;M++)"
     "{"
       "float d=w(v+f*D).dist;"
       "if(d<.001)"
         "return 0.;"
       "float x=d*d/(2.*z),s=sqrt(d*d-x*x);"
       "r=min(r,s/(i*max(0.,D-x)));"
       "z=d;"
       "D+=d;"
     "}"
   "return r;"
 "}"
 "vec3 T(vec3 v,float f)"
 "{"
   "vec2 m=vec2(s(f+1.),s(f+2.));"
   "float i=m.x*y*2.,z=m.y*2.-1.;"
   "vec3 t=vec3(sin(i),cos(i),z)/sqrt(1.+z*z);"
   "return t*sign(dot(t,v));"
 "}"
 "float T(vec3 v,vec3 f,float y,float m)"
 "{"
   "float i=0.;"
   "for(int D=0;D<10;D++)"
     "{"
       "float z=s(float(D))*y;"
       "vec3 x=normalize(f+T(f,z)*.95)*z;"
       "i+=(z-w(v+x).dist)/pow(1.+z,m);"
     "}"
   "return clamp(1.-i*.1,0.,999.);"
 "}"
 "vec3 T(vec3 v)"
 "{"
   "vec3 f=vec3(.001,0.,0.);"
   "return normalize(vec3(w(v+f.xyy).dist-w(v-f.xyy).dist,w(v+f.yxy).dist-w(v-f.yxy).dist,w(v+f.yyx).dist-w(v-f.yyx).dist));"
 "}"
 "vec4 c(vec2 v,vec2 y,vec2 f,float m)"
 "{"
   "vec4 i;"
   "float d=1.-m;"
   "i.xy=d*d*v+2*d*m*y+m*m*f;"
   "i.zw=(2*m-2)*v+(2-4*m)*y+2*m*f;"
   "return i;"
 "}"
 "vec3 G(vec3 v,float y)"
 "{"
   "return v+(vec3(1)-v)*pow(1.-y,5);"
 "}"
 "vec2 G(vec2 v)"
 "{"
   "vec2 f=fract(v),m=floor(v);"
   "float y=100.,z=0.;"
   "for(int i=-1;i<=1;i++)"
     "for(int D=-1;D<=1;D++)"
       "{"
         "vec2 x=vec2(float(D),float(i)),c=m+x,s=n(c);"
         "float d=distance(f,s+x);"
         "if(d<y)"
           "y=d,z=t(c);"
       "}"
   "return vec2(max(0.,1.-y),z);"
 "}"
 "void main()"
 "{"
   "vec2 v=vec2(1920,1080),y=gl_FragCoord.xy/v.xy,r=-1.+2.*y;"
   "r.x*=v.x/v.y;"
   "M=vec3(0,1.6,-2);"
   "float G=x-t(gl_FragCoord.xy+x)/200.;"
   "vec4 n=c(i,z,a,G/30.);"
   "M.xz+=n.xy;"
   "vec2 C;"
   "M.y+=t(M.xz,s(M.xz,C));"
   "vec3 g=M;"
   "g.y+=.01*e(vec2(50*x,0));"
   "D=w(vec3(n.z,0,n.w),l(M.xz));"
   "vec3 p=normalize(vec3(r.x,r.y,1.7))*D;"
   "float h=0.;"
   "int S=-1;"
   "for(int o=0;o<512&&h<m;++o)"
     "{"
       "Map_Result A=w(g+h*p);"
       "float k=A.dist;"
       "if(abs(k)<.001*(1.+h))"
         "{"
           "S=A.mat_id;"
           "break;"
         "}"
       "h+=k;"
     "}"
   "vec3 o=1.4*vec3(.5,.6,.7);"
   "o=mix(o,.5*o,p.y);"
   "vec3 k=o,A=normalize(vec3(-.3,2.,1.));"
   "if(S!=-1)"
     "{"
       "vec3 u=g+h*p,R=T(u);"
       "vec2 I;"
       "float E=s(u.xz,I);"
       "vec3 b=vec3(1);"
       "if(S==CAR_MATERIAL_ID)"
         "b=vec3(.05);"
       "else"
         " if(S==STEERING_WHEEL_MATERIAL_ID)"
           "b=vec3(.05);"
         "else"
           " if(S==TERRAIN_MATERIAL_ID)"
             "if(E<=7.)"
               "{"
                 "b=vec3(.1);"
                 "if(E<=.15)"
                   "{"
                     "float L=step(1.3,mod(I.y,5.));"
                     "b=mix(b,vec3(.65),L);"
                   "}"
                 "if(E>6.3&&E<6.6)"
                   "b=vec3(.65);"
               "}"
             "else"
               " b=vec3(.35,.4,.2);"
       "float L=max(0,dot(R,A));"
       "vec3 N=b;"
       "float U=d(u,A,.023,m,.03);"
       "k=N*U*L;"
       "k+=.2*o*T(u,R,1.5,1.)*b;"
     "}"
   "f=vec4(sqrt(k),0.);"
 "}";

#endif // FRAGMENT_INL_
